### ISSUE TITLE
We Are Hiringセクションの"セキュリティエンジニア"がリンク切れ

### ISSUE THREAD

**Issue by nishim** [kufu/hello-world#114]
We Are Hiringセクションの"セキュリティエンジニア"がリンク切れとなっています。
開けないリンクのURLは https://open.talentio.com/r/1/c/smarthr/pages/45057 です。
あるべき姿への修正（隠す？リンク修正？talentio側での公開設定？）をお願いします。

### 修正が必要な箇所
https://github.com/kufu/hello-world/blob/f03c268ff94dd546fbc36dede4dc722f596793d8/src/components/parts/EntrySection.tsx#L45-L49

**Comment by mkmn** [comment]
@nishim 
ありがとうございます！
現在セキュリティエンジニアは募集を停止しているため、リンクを隠す対応をさせていただきます 🙏

**Comment by nishim** [comment]
@mkmn 
↓2つ確認しました。どちらも問題ないですし、閉じますね。
- https://hello-world.smarthr.co.jp
- https://github.com/kufu/hello-world/pull/115

素早い対応素敵です。見習います。
