### ISSUE TITLE
[feature request] 🔗株式会社SmartHR 様ホームページへの導線が欲しい

### ISSUE THREAD

**Issue by noritakaIzumi** [kufu/hello-world#121]
## 概要

エンジニア採用サイトから株式会社SmartHR様ウェブサイト https://smarthr.co.jp/ へ移動できるリンクがあるといいのではないでしょうか？

## 経緯

機会がありまして、貴社エンジニア採用サイトを拝見させていただきました 👀 
その際、貴社ウェブサイトからエンジニア採用サイトへの導線はあるのですが、その逆の導線がないのが気になりました 🤔 

現在 Google 検索で `SmartHR 採用サイト` と検索するとエンジニア採用サイトそのものも結果に上がってきているため、
「エンドユーザが Google 検索から直接エンジニア採用サイトに遷移」→「その後貴社ウェブサイトへ移動」のケースが想定されるのではないかと考えます。

差し支えなければご検討くださいませ 🙇

**Comment by yoshinarl** [comment]
@noritakaIzumi ありがとうございます！
仰るとおりだと思いましたので検討させていただきます 🙏

**Comment by f440** [comment]
確認したところご指摘の通りなので、ロゴをリンクにして会社サイト側に遷移できるようにしました。コメントありがとうございます！
