### ISSUE TITLE
Chrome拡張機能のPocketが入っているとコマンドパレットが表示されない

### ISSUE THREAD

**Issue by chidoriashi1990** [kufu/hello-world#89]
Chrome拡張機能のPocketのショートカットキーも`cmd+Shift+p`のため、Pocketが優先されてコマンドパレットが表示されない事象が確認された

## 動作環境
- Chrome バージョン: 91.0.4472.77（Official Build） （x86_64）
- Chrome拡張機能[Pocket](https://getpocket.com/)

**Comment by machupicchubeta** [comment]
@chidoriashi1990 
I encountered the same issue and reconfigured the shortcut key for Pocket (Chrome Extension).
I hope this helps you.

Pocket (Chrome Extension) settings page URL is:
- chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/pages/options/options.html

**Comment by chidoriashi1990** [comment]
@machupicchubeta 
Thank you for letting me know.
I set it up using your info and it worked out!
